# Generated by Django 4.2.4 on 2023-08-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='boo',
            field=models.BooleanField(default=False),
        ),
    ]
